dist:
  name: slim-otelcol
  description: Basic OTel Collector distribution for Developers
  output_path: ./slim-otelcol
  otelcol_version: 0.143.0

replaces:
  - github.com/agntcy/slim/otel => ..
  - github.com/agntcy/slim/otel/slimexporter => ../slimexporter

exporters:
  - gomod: github.com/agntcy/slim/otel/slimexporter v0.0.1
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.143.0

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.143.0

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.143.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.48.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.48.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.48.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.48.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.48.0

