# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: ci-test-and-build-otel

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  otel-build-and-test:
    name: SLIM OpenTelemetry Collector - build & test
    uses: ./.github/workflows/reusable-go-otel-build-and-test.yaml

    with:
      go-version: 1.25.4
      cgo-enabled: '1'
      go-check-gencode: false
      go-check-multimod: false      
